<?php

/**
 * @file
 * Contains unt_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function unt_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the unt_events module.
    case 'help.page.unt_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pulls Events from the campus events site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function unt_events_theme($existing, $type, $theme, $path) {
  return [
    'unt_events_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'render element' => 'children',
    ],
    'unt_events_event_detail' => [
      'variables' => [
        'title' => NULL,
        'date' => NULL,
        'location' => NULL,
        'image' => NULL,
        'contact_name' => NULL,
        'contact_email' => NULL,
        'contact_phone' => NULL,
        'details' => NULL,
        'department' => NULL,
      ],
      'render element' => 'children',
    ]
  ];
}
